name: Merge Gate

on:
  pull_request:
    branches:
      - main
      - snowflake-*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Build Spark
      run: |
        chmod +x build/build-spark.sh
        chmod +x build/update-version.sh
        ./build/build-spark.sh
      env:
        MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g
    
    - name: Run Selective Tests  
      run: |
        chmod +x build/run-selective-tests.sh
        if [ -f "test-config/test-allowlist-pr-${{ github.event.pull_request.number }}.txt" ]; then
          ./build/run-selective-tests.sh "test-config/test-allowlist-pr-${{ github.event.pull_request.number }}.txt"
        else
          ./build/run-selective-tests.sh
        fi
      env:
        MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g
